<?php

return [
    //--------------------------------------------------
    [
        'name' => 'Add Group',
        'slug' => 'add-group',
        'is_crud' => true,
        'module' => 'Group & Permission',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Group',
        'slug' => 'edit-group',
        'is_crud' => true,
        'module' => 'Group & Permission',
        'action' => 'Edit',
    ],
    [
        'name' => 'Delete Group',
        'slug' => 'delete-group',
        'is_crud' => true,
        'module' => 'Group & Permission',
        'action' => 'Delete',
    ],
    [
        'name' => 'View Group List',
        'slug' => 'view-group',
        'is_crud' => true,
        'module' => 'Group & Permission',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add User',
        'slug' => 'add-user',
        'is_crud' => true,
        'module' => 'Users',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit User',
        'slug' => 'edit-user',
        'is_crud' => true,
        'module' => 'Users',
        'action' => 'Edit',
    ],
    [
        'name' => 'View User',
        'slug' => 'view-user',
        'is_crud' => true,
        'module' => 'Users',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'View Attribute',
        'slug' => 'view-attribute',
        'is_crud' => true,
        'module' => 'Attribute',
        'action' => 'View',
    ],
    [
        'name' => 'Edit Attribute',
        'slug' => 'edit-attribute',
        'is_crud' => true,
        'module' => 'Attribute',
        'action' => 'Edit',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Option',
        'slug' => 'add-option',
        'is_crud' => true,
        'module' => 'Options',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Option',
        'slug' => 'edit-option',
        'is_crud' => true,
        'module' => 'Options',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Options',
        'slug' => 'view-option',
        'is_crud' => true,
        'module' => 'Options',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Collection',
        'slug' => 'add-collection',
        'is_crud' => true,
        'module' => 'Collection',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Collection',
        'slug' => 'edit-collection',
        'is_crud' => true,
        'module' => 'Collection',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Collection',
        'slug' => 'view-collection',
        'is_crud' => true,
        'module' => 'Collection',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Category',
        'slug' => 'add-category',
        'is_crud' => true,
        'module' => 'Category',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Category',
        'slug' => 'edit-category',
        'is_crud' => true,
        'module' => 'Category',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Category',
        'slug' => 'view-category',
        'is_crud' => true,
        'module' => 'Category',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Sub Category',
        'slug' => 'add-sub-category',
        'is_crud' => true,
        'module' => 'Sub Category',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Sub Category',
        'slug' => 'edit-sub-category',
        'is_crud' => true,
        'module' => 'Sub Category',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Sub Category',
        'slug' => 'view-sub-category',
        'is_crud' => true,
        'module' => 'Sub Category',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Product',
        'slug' => 'add-product',
        'is_crud' => true,
        'module' => 'Product',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Product',
        'slug' => 'edit-product',
        'is_crud' => true,
        'module' => 'Product',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Product',
        'slug' => 'view-product',
        'is_crud' => true,
        'module' => 'Product',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Assign Attribute',
        'slug' => 'assign-attribute',
        'is_crud' => false,
        'module' => 'Other',
        'action' => 'Assign Attribute',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Discount',
        'slug' => 'add-discount',
        'is_crud' => true,
        'module' => 'Discount',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Discount',
        'slug' => 'edit-discount',
        'is_crud' => true,
        'module' => 'Discount',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Discount',
        'slug' => 'view-discount',
        'is_crud' => true,
        'module' => 'Discount',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Edit Customer',
        'slug' => 'edit-customer',
        'is_crud' => true,
        'module' => 'Customer',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Customer',
        'slug' => 'view-customer',
        'is_crud' => true,
        'module' => 'Customer',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'View Inquiry Contact',
        'slug' => 'view-inquiry-contact',
        'is_crud' => false,
        'module' => 'Inquiry',
        'action' => 'Contact',
    ],
    [
        'name' => 'View Inquiry Product',
        'slug' => 'view-inquiry-product',
        'is_crud' => false,
        'module' => 'Inquiry',
        'action' => 'Product',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Email Template',
        'slug' => 'add-email-template',
        'is_crud' => true,
        'module' => 'Email Template',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Email Template',
        'slug' => 'edit-email-template',
        'is_crud' => true,
        'module' => 'Email Template',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Email Template',
        'slug' => 'view-email-template',
        'is_crud' => true,
        'module' => 'Email Template',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Edit Offer',
        'slug' => 'edit-offer',
        'is_crud' => true,
        'module' => 'Offer',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Offer',
        'slug' => 'view-offer',
        'is_crud' => true,
        'module' => 'Offer',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Services',
        'slug' => 'add-service',
        'is_crud' => true,
        'module' => 'Services',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Services',
        'slug' => 'edit-service',
        'is_crud' => true,
        'module' => 'Services',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Services',
        'slug' => 'view-service',
        'is_crud' => true,
        'module' => 'Services',
        'action' => 'View',
    ],
    [
        'name' => 'Delete Services',
        'slug' => 'delete-service',
        'is_crud' => true,
        'module' => 'Services',
        'action' => 'Delete',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Testimonial',
        'slug' => 'add-testimonial',
        'is_crud' => true,
        'module' => 'Testimonial',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Testimonial',
        'slug' => 'edit-testimonial',
        'is_crud' => true,
        'module' => 'Testimonial',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Testimonial',
        'slug' => 'view-testimonial',
        'is_crud' => true,
        'module' => 'Testimonial',
        'action' => 'View',
    ],
    [
        'name' => 'Delete Testimonial',
        'slug' => 'delete-testimonial',
        'is_crud' => true,
        'module' => 'Testimonial',
        'action' => 'Delete',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add FAQ Category',
        'slug' => 'add-faq-category',
        'is_crud' => true,
        'module' => 'FAQ Category',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit FAQ Category',
        'slug' => 'edit-faq-category',
        'is_crud' => true,
        'module' => 'FAQ Category',
        'action' => 'Edit',
    ],
    [
        'name' => 'View FAQ Category',
        'slug' => 'view-faq-category',
        'is_crud' => true,
        'module' => 'FAQ Category',
        'action' => 'View',
    ],
    [
        'name' => 'Delete FAQ Category',
        'slug' => 'delete-faq-category',
        'is_crud' => true,
        'module' => 'FAQ Category',
        'action' => 'Delete',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add FAQ Information',
        'slug' => 'add-faq-information',
        'is_crud' => true,
        'module' => 'FAQ Information',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit FAQ Information',
        'slug' => 'edit-faq-information',
        'is_crud' => true,
        'module' => 'FAQ Information',
        'action' => 'Edit',
    ],
    [
        'name' => 'View FAQ Information',
        'slug' => 'view-faq-information',
        'is_crud' => true,
        'module' => 'FAQ Information',
        'action' => 'View',
    ],
    [
        'name' => 'Delete FAQ Information',
        'slug' => 'delete-faq-information',
        'is_crud' => true,
        'module' => 'FAQ Information',
        'action' => 'Delete',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Blog',
        'slug' => 'add-blog',
        'is_crud' => true,
        'module' => 'Blog',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Blog',
        'slug' => 'edit-blog',
        'is_crud' => true,
        'module' => 'Blog',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Blog',
        'slug' => 'view-blog',
        'is_crud' => true,
        'module' => 'Blog',
        'action' => 'View',
    ],
    [
        'name' => 'Delete Blog',
        'slug' => 'delete-blog',
        'is_crud' => true,
        'module' => 'Blog',
        'action' => 'Delete',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add User Manu',
        'slug' => 'add-user-menu',
        'is_crud' => true,
        'module' => 'User Manu',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit User Manu',
        'slug' => 'edit-user-menu',
        'is_crud' => true,
        'module' => 'User Manu',
        'action' => 'Edit',
    ],
    [
        'name' => 'View User Manu',
        'slug' => 'view-user-menu',
        'is_crud' => true,
        'module' => 'User Manu',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'View Subscriber',
        'slug' => 'view-subscriber',
        'is_crud' => false,
        'module' => 'Other',
        'action' => 'Email Subscribers',
    ],
    //--------------------------------------------------
    [
        'name' => 'Language',
        'slug' => 'language-setting',
        'is_crud' => false,
        'module' => 'Setting',
        'action' => 'Language',
    ],
    [
        'name' => 'General',
        'slug' => 'general-setting',
        'is_crud' => false,
        'module' => 'Setting',
        'action' => 'General',
    ],
    [
        'name' => 'Social Link',
        'slug' => 'social-link-setting',
        'is_crud' => false,
        'module' => 'Setting',
        'action' => 'Social Link',
    ],
    [
        'name' => 'Homepage',
        'slug' => 'homepage-setting',
        'is_crud' => false,
        'module' => 'Setting',
        'action' => 'Homepage',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Payment Gateway',
        'slug' => 'add-payment-gateway',
        'is_crud' => true,
        'module' => 'Payment Gateway',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Payment Gateway',
        'slug' => 'edit-payment-gateway',
        'is_crud' => true,
        'module' => 'Payment Gateway',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Payment Gateway',
        'slug' => 'view-payment-gateway',
        'is_crud' => true,
        'module' => 'Payment Gateway',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Custom Category',
        'slug' => 'add-custom-category',
        'is_crud' => true,
        'module' => 'Custom Category',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Custom Category',
        'slug' => 'edit-custom-category',
        'is_crud' => true,
        'module' => 'Custom Category',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Custom Category',
        'slug' => 'view-custom-category',
        'is_crud' => true,
        'module' => 'Custom Category',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Custom Sub Category',
        'slug' => 'add-custom-sub-category',
        'is_crud' => true,
        'module' => 'Custom Sub Category',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Custom Sub Category',
        'slug' => 'edit-custom-sub-category',
        'is_crud' => true,
        'module' => 'Custom Sub Category',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Custom Sub Category',
        'slug' => 'view-custom-sub-category',
        'is_crud' => true,
        'module' => 'Custom Sub Category',
        'action' => 'View',
    ],
    //--------------------------------------------------
    [
        'name' => 'Add Banner',
        'slug' => 'add-banner',
        'is_crud' => true,
        'module' => 'Banner',
        'action' => 'Add',
    ],
    [
        'name' => 'Edit Banner',
        'slug' => 'edit-banner',
        'is_crud' => true,
        'module' => 'Banner',
        'action' => 'Edit',
    ],
    [
        'name' => 'View Banner',
        'slug' => 'view-banner',
        'is_crud' => true,
        'module' => 'Banner',
        'action' => 'View',
    ],
    [
        'name' => 'Delete Banner',
        'slug' => 'delete-banner',
        'is_crud' => true,
        'module' => 'Banner',
        'action' => 'Delete',
    ],
];
